### ISSUE TITLE
Wrong link to set cloud monitoring permission

### ISSUE THREAD

**Issue by huikang** [IBM-Bluemix-Docs/cloud-monitoring#3]
In Step 2(4) [1], the  monitoring service is not in Access policies > Assign Access > Assign access to resources. It should belong to  Access policies > Assign Access > **Cloud Foundry access** .

[1] https://github.com/IBM-Bluemix-Docs/cloud-monitoring/blob/master/tutorials/container_service_metrics.md#step-2-grant-your-user-permissions-to-see-metrics-in-the-account-domain

**Comment by lopezdsr** [comment]
The Monitoring service requires an IAM policy to view cluster metrics that are available through the account domain. Cluster forward metrics to the Monitoring service account domain. 

CF access is required for metrics that are available through a space domain.
