### ISSUE TITLE
Add that monitoring is available for standard clusters only

### ISSUE THREAD

**Issue by Nadine2016** [IBM-Bluemix-Docs/cloud-monitoring#4]
Alison Lucas [8:29 AM]
Hi, does anyone know why you can't send data to an IBM Cloud Monitoring service if it's a free service, please? Nothing in the docs to say you can't (https://console.bluemix.net/docs/services/cloud-monitoring/send-metrics/conf_monitoring_plugin.html#conf_monitoring_plugin) but when I try it fails: Mar 16 10:41:33 zbc02b collectd[116095]: {"message":"IBM Cloud Monitoring Plugin: BXNMSMG02E: Metrics can only be accepted on a paid plan","level":"

 Jake Kitchener [1 hour ago]
you need to upgrade to a paid plan

Jake Kitchener [1 hour ago]
its not free

Jake Kitchener [1 hour ago]
https://console.bluemix.net/catalog/services/monitoring?taxonomyNavigation=apps
console.bluemix.net
Monitoring - IBM Cloud
Empower your DevOps team with IBM Cloud Monitoring for insight into how your apps are performing and consuming resources. Quickly identify trends, detect and diagnose problems; all with immediate time to value and low total cost of ownership. Upgrade to the premium plan to expand your collection and retention abilities.

Jake Kitchener [1 hour ago]
there is a premium plan you can pay for

Jake Kitchener [1 hour ago]
Premium Monitoring
Metric collection with 45 days retention
Alerts: alerting rules including wild cards
$2.00 USD/Million data points ingested per month
$0.10 USD/Single metric alerting rules per month

@lopezdsr

**Comment by lopezdsr** [comment]
The docs do say that for metric ingestion a paid plan is required: See https://console.bluemix.net/docs/services/cloud-monitoring/monitoring_ov.html#plan
