### ISSUE TITLE
Can not find space name of my bluemix container cluster

### ISSUE THREAD

**Issue by huikang** [IBM-Bluemix-Docs/cloud-monitoring#7]
Following the answer to this question "How do I find the space ID and space name of a space that is associated with a cluster?" on this page [1], I can not see the ``Log Space`` field. For example, here is the output for my cluster

```
Name:			ctrl-staging
ID:			3a8d08d79ad24b839e43b3e5871686f6
State:			normal
Created:		2017-11-08T15:35:35+0000
Location:		dal12
Master URL:		https://169.47.70.10:27298
Ingress Subdomain:	xxxx.us-south.containers.mybluemix.net
Ingress Secret:		xxxx
Workers:		2
Version:		1.8.13_1514* (1.9.8_1515 latest)
Owner Email:		kangh@us.ibm.com
Monitoring Dashboard:	https://metrics.ng.bluemix.net/app/#/grafana4/dashboard/db/a-c250c68aa578d4d8eb1752e3d7da54be_ClusterMonitoringDashboard_v4?scopeId=a-c250c68aa578d4d8eb1752e3d7da54be&?var-Account_ID=a_c250c68aa578d4d8eb1752e3d7da54be&var-Cluster=ctrl-staging&var-Namespace=default&var-Pod_ID=All

```

Is the log space field deprecated? Thanks.

[1] https://console.bluemix.net/docs/services/cloud-monitoring/qa/qa_containers.html#qa2

**Comment by lopezdsr** [comment]
Thank you for the feedback. 

Yes, it has been deprecated. 

I will update docs to reflect change.
